# Generated by Django 3.1 on 2020-08-22 20:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=22, validators=[django.core.validators.RegexValidator(message='Номер телефона может содержать только цифры, пробелы и дефисы', regex='^(\\+7|8|0)?(?:(\\s|-)?\\d{1,4}){2,4}$')], verbose_name='номер')),
            ],
            options={
                'verbose_name': 'номер телефона',
                'verbose_name_plural': 'номера телефонов',
            },
        ),
    ]
