# Generated by Django 3.1 on 2020-08-22 15:55

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import page_components.models.blocks
import page_components.models.fields
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='homepage',
            options={'verbose_name': 'Главная страница'},
        ),
        migrations.AddField(
            model_name='homepage',
            name='background_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='фоновое изображение'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='features',
            field=page_components.models.fields.HeroFeaturesField(blank=True, default='Lorem Ipsum', help_text='Подробная характеристика', verbose_name='особенности'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='summary',
            field=models.CharField(default='Lorem Ipsum', help_text='Суть продукта/услуги', max_length=100, verbose_name='заглавный текст'),
        ),
        migrations.CreateModel(
            name='HomePageSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('heading', models.CharField(default='Lorem Ipsum', help_text='Тема раздела', max_length=100, verbose_name='заголовок')),
                ('subheading', models.CharField(blank=True, default='Lorem Ipsum', max_length=80, verbose_name='подзаголовок')),
                ('body', wagtail.core.fields.StreamField([('paragraph', page_components.models.blocks.ParagraphBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(help_text='Иллюстрирование текста', label='Изображение')), ('embed', wagtail.embeds.blocks.EmbedBlock(help_text='Например, видео с YouTube', label='Встраиваемое медиа'))], verbose_name='содержание')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='home.homepage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
